#!/bin/bash

export TZ=Asia/Shanghai

cd /root/Main

if [ -e "/root/Main/version.txt" ]; then

    flag=`git pull | grep "Updating" | wc -l`
    if [ $flag = "1" ]; then
        echo "[`date`] need update" >> /root/update.log
        /usr/bin/killall watchdog Main captureService testOnDemandRTSPServer
        /bin/bash postUpdate
        /usr/bin/make
        /bin/sync
        /sbin/reboot
    else
        echo "[`date`] no update" >> /root/update.log
    fi
else
    echo "[`date`] no version.txt, skip update" >> /root/update.log
fi

if [ ! -e "/etc/cron.hourly/syncDate" ]; then
    cp /root/Main/syncDate /etc/cron.hourly/
    echo "copy syncDate file success".
fi

md5_syncDate=`md5sum /etc/cron.hourly/syncDate | awk '{print $1}'`;
md5_syncDate_2=`md5sum syncDate | awk '{print $1}'`;

echo "md5[etc syncDate] "$md5_syncDate
echo "md5[syncDate] "$md5_syncDate_2

if [ "$md5_syncDate" != "$md5_syncDate_2" ]; then
    echo "change syncDate"
    cp /root/Main/syncDate /etc/cron.hourly/
fi


