#!/bin/bash

cd /root/Main

if [ -e "/root/Main/version.txt" ]; then

    flag=`git pull | grep "Updating" | wc -l`
    if [ $flag = "1" ]; then
        echo "[`date`] need update" >> /root/update.log
        make && sync
        /sbin/reboot
    else
        echo "[`date`] no update" >> /root/update.log
    fi
else
    echo "[`date`] no version.txt, skip update" >> /root/update.log
fi
